### ISSUE TITLE
Config options don't work

### ISSUE THREAD

**Issue by thelastredshirt** [frdteknikelektro/MMM-SimpleLogo#1]
Default logo, width, and position are always used, despite settings in config.js.

Changing "defaults" to "config" worked, but not sure if that's the proper fix. Unpopulated config options remained the default values.

Using Firefox 50.1.0.

[config_patch.txt](https://github.com/frdteknikelektro/MMM-SimpleLogo/files/704964/defaults_config.txt)

**Comment by frdteknikelektro** [comment]
Hey, you right!
Thanks for the patch, please see [v1.0.1](https://github.com/frdteknikelektro/MMM-SimpleLogo/releases/tag/v1.0.1)

**Comment by thelastredshirt** [comment]
No issues with the latest release. :)
