### ISSUE TITLE
Custom CSS & Top Text

### ISSUE THREAD

**Issue by SdeGeata** [frdteknikelektro/MMM-SimpleLogo#14]
Hello;

   I have been playing with the Top Text and dynamically changing it as well as the images using `.../api/notification/SIMPLE_LOGO_UPDATE...`. It is all working great!

   I would however like to modify the Top Text to be a little larger and perhaps centred. I can't seem to get anything to work using custom.css, it is not referenced at all in the module's css file either. How can I modify this text?

**Comment by frdteknikelektro** [comment]
Maybe you could add styles for
https://github.com/frdteknikelektro/MMM-SimpleLogo/blob/develop/css/mmm-simplelogo.css

**Comment by SdeGeata** [comment]
Hey there @frdteknikelektro !


   Thanks for your reply. I don't know how I missed that line with the font tag. (face slap)

Thanks for your help.
