### ISSUE TITLE
[Feature Request] Automatic refresh of image when change is detected

### ISSUE THREAD

**Issue by ElYoM** [frdteknikelektro/MMM-SimpleLogo#2]
Hello,

I am currently using your module and I was wondering if it was possible to implement an automatic image refresh system when a change is detected or after a configurable delay?  I ask for this because I generate an image of the sunshine of the Earth using Xplanet every 2 minutes and then I display it using your module and I really want these changes to appear automatically without having to restart the entire MagicMirror application.

Thank you in advance.
![2017-02-14_00-27-45](https://cloud.githubusercontent.com/assets/18171050/22940298/b1c981aa-f2e1-11e6-9c43-18dad321e0bb.png)

**Comment by frdteknikelektro** [comment]
Hi! Wow, that's awesome, could you show module config in you config js for simple-logo module?

**Comment by ElYoM** [comment]
Hello, I have not modified the configuration options of the module, it is the default options that are used. I just generate an image of the Earth with Xplanet every two minutes and this image is saved instead of the module's logo.png file. ;)

`{
			module: 'MMM-SimpleLogo',
			position: 'middle_center',   // This can be any of the regions.
			config: {
            // The config property is optional.
            // See 'Configuration options' for more information.
				fileUrl: 'modules/MMM-SimpleLogo/public/logo.png',
				width: '600px',
				position: 'center',
			}
		},`

**Comment by frdteknikelektro** [comment]
So you just save the picture in folder 'modules/MMM-SimpleLogo/public' and save it with name 'logo.png'?
Are you generate the image of the Earth automatically?

**Comment by ElYoM** [comment]
Hello, 
Yes, this is right. Xplanet automatically generates a new image every two minutes and overwrites the logo.png file located in the 'modules / MMM-SimpleLogo / public' directory. Do you think it is possible to add an automatic refresh mechanism of the image file ?

**Comment by frdteknikelektro** [comment]
Yes, of course, it's possible, let me notify you if the patch is done.

**Comment by ElYoM** [comment]
Awesome ! Thank you very much.

**Comment by frdteknikelektro** [comment]
Check this out [v1.1.0](https://github.com/frdteknikelektro/MMM-SimpleLogo/releases/tag/v1.1.0).

Your project is awesome, you should do a time-lapse video! Please post your project when you're done! and let me notified

**Comment by ElYoM** [comment]
Excellent work ! Thank you for everything. I will test these changes and I will come back to you in case of bug finds. I will try to make a time-lapse video of the final render.
