### ISSUE TITLE
feature request: label

### ISSUE THREAD

**Issue by kibotu** [frdteknikelektro/MMM-SimpleLogo#6]
i know it's supposed to be a simple logo, but can we have a label please? :D 

i was planning on adding a bunch of them to display build-server builds, e.g.: [![Build Status](https://travis-ci.org/kibotu/Heart-Rate-Ometer.svg?branch=master)](https://travis-ci.org/kibotu/Heart-Rate-Ometer)

**Comment by frdteknikelektro** [comment]
Could you just paste the url?
in your case this link https://camo.githubusercontent.com/fc74659f9ad4d2c13e2378c36ae08367d3f4acbd/68747470733a2f2f7472617669732d63692e6f72672f6b69626f74752f48656172742d526174652d4f6d657465722e7376673f6272616e63683d6d6173746572

**Comment by kibotu** [comment]
ah sorry sure https://travis-ci.org/kibotu/Heart-Rate-Ometer.svg?branch=master

**Comment by frdteknikelektro** [comment]
@kibotu please check cc40947b. If you are using refresh interval feature the release before this should be broken. Try this new release.
but if you didn't use fetch interval feature. its will be okay.
